version: '2'

services:
  web12:
    image: odoo:12.0
    container_name: odoo12
    depends_on:
      - db
    ports:
      - "8067:8069"
    volumes:
      - odoo-web-12-data:/var/lib/odoo
      - ./config/odoo12:/etc/odoo
      - ./addons/odoo12:/mnt/extra-addons
      - ./addons/All:/mnt/extra-addons-all
    networks: 
      - odoo

  web13:
    image: odoo:13.0
    container_name: odoo13
    depends_on:
      - db
    ports:
      - "8068:8069"
    volumes:
      - odoo-web-13-data:/var/lib/odoo
      - ./config/odoo13:/etc/odoo
      - ./addons/odoo13:/mnt/extra-addons
      - ./addons/All:/mnt/extra-addons-all
    networks: 
      - odoo

  web:
    image: odoo:14.0
    container_name: odoo14
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-14-data:/var/lib/odoo
      - ./config/odoo14:/etc/odoo
      - ./addons/odoo14-addons:/usr/lib/python3/dist-packages/odoo/addons
      - ./addons/odoo14:/mnt/extra-addons
      - ./addons/All:/mnt/extra-addons-all
    networks: 
      - odoo

  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pangsoramdepo@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=depo1234
    networks: 
      - odoo

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks: 
      odoo:
        ipv4_address: 172.16.1.9

networks:
  odoo:
    external: true

volumes:
  odoo-web-12-data:
  odoo-web-13-data:
  odoo-web-14-data:
